# Generated by Django 3.0.5 on 2020-05-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('anho', models.IntegerField()),
                ('editor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='puntuacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUs', models.IntegerField()),
                ('isbn', models.IntegerField()),
                ('puntuacion', models.IntegerField()),
            ],
        ),
    ]
